from pathlib import Path
import json,re,sys
ROOT=Path(__file__).resolve().parents[1]
app=(ROOT/'assets/js/app.js').read_text(encoding='utf-8')
data=(ROOT/'assets/js/data.js').read_text(encoding='utf-8')
safety=(ROOT/'assets/js/safety.js').read_text(encoding='utf-8')
html=(ROOT/'index.html').read_text(encoding='utf-8')
css=(ROOT/'assets/css/styles.css').read_text(encoding='utf-8')
sw=(ROOT/'sw.js').read_text(encoding='utf-8')
manifest=json.loads((ROOT/'manifest.webmanifest').read_text(encoding='utf-8'))
platform=(ROOT/'assets/js/platform.js').read_text(encoding='utf-8')
checks=[]
def ck(n,v): checks.append((n,bool(v)))
ck('exact title','Moner Kotha: Anonymous Social Site' in html and manifest.get('name')=='Moner Kotha: Anonymous Social Site')
ck('localized brand and fixed slogan','brandName' in app and 'কথা বলুন মন খুলে' in html)
mood_section=data.split('export const needMeta',1)[0]
ck('relationship topic only','relationship: { bn: "রিলেশন"' in data and 'relationship' not in mood_section)
ck('married life topic only','postMarriage: { bn: "দাম্পত্য জীবন"' in data and 'postMarriage' not in mood_section)
ck('other and skip choices','\"other\": {' in data.split('export const needMeta',1)[0] and 'customMoodPlaceholder' in app and 'customSupportPlaceholder' in app and '__skip__' in app)
ck('personal and jobs groups','personal-life' in data and 'jobs-pressure' in data)
ck('no user links or restricted sensitive content','validateCommunityText' in app and 'containsLink' in safety and 'containsProhibitedSensitiveContent' in safety)
ck('post ranking and filter','postRankScore' in app and 'data-feed="ranking"' in html)
ck('post TTL','POST_TTL_MS=183*24*60*60*1000' in app and 'expiresAt' in app)
ck('profile post management','profile-post-row' in app and 'data-edit-post' in app and 'data-delete-post' in app)
ck('48 hour moments','MOMENT_TTL_MS=48*60*60*1000' in app and 'compose-moment' in app)
ck('hundreds of mood choices','export const momentMoods' in data and data.count('\"group\"')>=200)
ck('moment empathy ranking','momentScore' in app and 'momentReactions' in app)
ck('notification scaffold','enable-notifications' in app and 'test-notification' in app and 'subscribePush' in app and 'subscriptionEndpoint' in app and 'addEventListener("push"' in sw)
ck('logo professional integration','logo-mark.png' in html and not manifest.get('shortcuts'))
ck('Ctrl K removed','Ctrl K' not in html and '<kbd' not in html)
ck('get help back control','setPage(`${pageHeader(t("safetyTitle"))}' in app and 'data-action="back-page"' in app)
ck('desktop edit profile card','edit-profile-card' in html and 'data-action="profile"' in html)
ck('normal phone browser and phone PWA use mobile; desktop-site request stays desktop','const useMobileLayout = platform.layout === "mobile"' in app and 'const phoneAppLayout = Boolean(isPhone && (standalone || !desktopSiteRequested))' in platform)
ck('cache 5.1+',tuple(map(int,re.search(r'const VERSION = "(\d+)\.(\d+)\.(\d+)"',sw).groups())) >= (5,1,0))
for n,o in checks: print(('PASS' if o else 'FAIL'),'-',n)
print(f'\n{sum(o for _,o in checks)}/{len(checks)} checks passed')
if not all(o for _,o in checks): sys.exit(1)
