from pathlib import Path
import re
ROOT=Path(__file__).resolve().parents[1]
app=(ROOT/'assets/js/app.js').read_text(encoding='utf-8')
index=(ROOT/'index.html').read_text(encoding='utf-8')
css=(ROOT/'assets/css/styles.css').read_text(encoding='utf-8')
sw=(ROOT/'sw.js').read_text(encoding='utf-8')
video=(ROOT/'assets/js/video_catalog.js').read_text(encoding='utf-8')
public_bn=(ROOT/'bn/index.html').read_text(encoding='utf-8')
public_en=(ROOT/'en/index.html').read_text(encoding='utf-8')
about_bn=(ROOT/'bn/about/index.html').read_text(encoding='utf-8')
about_en=(ROOT/'en/about/index.html').read_text(encoding='utf-8')
checks=[]
def ck(name, ok): checks.append((name,bool(ok))); print(('PASS' if ok else 'FAIL'),'-',name)
ck('exact Bangla composer heading','না বলতে পারা কথাগুলো প্রাণ খুলে বলুন' in app)
ck('4000 character post limit','maxlength="4000"' in app and '/4000' in app and '.slice(0,4000)' in app)
ck('Islamic and Video feed tabs','data-feed="islamic"' in index and 'data-feed="video"' in index)
ck('Islamic four subtabs','islamicTabs' in app and 'islamic-video' in (ROOT/'assets/js/islamic.js').read_text(encoding='utf-8'))
ck('Quran Bengali and audio adapters','loadQuranItems' in app and 'quranAudioUrl' in (ROOT/'assets/js/islamic.js').read_text(encoding='utf-8'))
ck('YouTube privacy enhanced embed','youtube-nocookie.com' in (ROOT/'assets/js/youtube_player.js').read_text(encoding='utf-8'))
ck('short and regular caps','shortMaxSeconds' in (ROOT/'config/site.json').read_text(encoding='utf-8') and 'playbackCapSeconds' in video)
ck('80 general video records architecture','CORE_MOODS.flatMap' in video and 'generalVideoCatalog=expand' in video)
ck('80 Islamic video records architecture','islamicVideoCatalog=expand' in video)
ck('YouTube thumbnail adapter','i.ytimg.com/vi' in video and 'createAdminVideoDraft' in video)
ck('Islamic section ad-free','setAdSafeMode(true,"islamic-section")' in app)
ck('general video ad placement','context:"video"' in app)
ck('independent desktop scrolling','overflow-y:auto' in css and '.left-rail,body.force-desktop-layout .feed-column,body.force-desktop-layout .right-rail' in css)
ck('compact mood chooser','.mood-select-button{min-height:48px' in css)
ck('direct native install prompt','const result=await pwa.promptInstall();' in app)
ck('automatic service worker activation','await self.skipWaiting()' in sw and 'await self.clients.claim()' in sw)
ck('periodic update checks','setInterval(()=>registration?.update?.()' in (ROOT/'assets/js/pwa.js').read_text(encoding='utf-8'))
ck('main logo on localized pages','/assets/brand/logo-mark.png' in public_bn and '/assets/brand/logo-mark.png' in public_en and '/assets/icons/icon-192.png' not in public_bn)
ck('video ownership notice','ভিডিও সম্পর্কিত ঘোষণা' in about_bn and 'Video content notice' in about_en)
ck('service worker 5.2+',tuple(map(int,re.search(r'const VERSION = "(\d+)\.(\d+)\.(\d+)"',sw).groups())) >= (5,2,0))
failed=[n for n,o in checks if not o]
print(f'{len(checks)-len(failed)}/{len(checks)} V5.2 checks passed')
raise SystemExit(1 if failed else 0)
